set -ogq @theme "everforest"
set -ogq @theme_switch_key "T"

set -ogq @theme_status_background "default"

set -ogq @theme_menu_selected_style "fg=#{@thm_fg},bold,bg=#{@thm_overlay_0}"

set -ogq @theme_pane_status_enabled "no" # set to "yes" to enable
set -ogq @theme_pane_border_status "off" # set to "yes" to enable
set -ogq @theme_pane_border_style "fg=#{@thm_overlay_0}"
set -ogq @theme_pane_active_border_style "##{?pane_in_mode,fg=#{@thm_lavender},##{?pane_synchronized,fg=#{@thm_mauve},fg=#{@thm_lavender}}}"
set -ogq @theme_pane_left_separator "█"
set -ogq @theme_pane_middle_separator "█"
set -ogq @theme_pane_right_separator "█"
set -ogq @theme_pane_color "#{@thm_green}"
set -ogq @theme_pane_background_color "#{@thm_surface_0}"
set -ogq @theme_pane_default_text "##{b:pane_current_path}"
set -ogq @theme_pane_default_fill "number"
set -ogq @theme_pane_number_position "left" # right, left

set -ogq @theme_window_status_style "basic" # basic, rounded, slanted, custom, or none
set -ogq @theme_window_text_color "#{@thm_surface_0}"
set -ogq @theme_window_number_color "#{@thm_overlay_2}"
set -ogq @theme_window_text " #T"
set -ogq @theme_window_number "#I"
set -ogq @theme_window_current_text_color "#{@thm_surface_1}"
set -ogq @theme_window_current_number_color "#{@thm_mauve}"
set -ogq @theme_window_current_text " #T"
set -ogq @theme_window_current_number "#I"
set -ogq @theme_window_number_position "left"

set -ogq @theme_window_flags "none"
set -ogq @theme_window_flags_icon_last " 󰖰" # -
set -ogq @theme_window_flags_icon_current " 󰖯" # *
set -ogq @theme_window_flags_icon_zoom " 󰁌" # Z
set -ogq @theme_window_flags_icon_mark " 󰃀" # M
set -ogq @theme_window_flags_icon_silent " 󰂛" # ~
set -ogq @theme_window_flags_icon_activity " 󱅫" # #
set -ogq @theme_window_flags_icon_bell " 󰂞" # !
set -ogq @theme_window_flags_icon_format "##{?window_activity_flag,#{E:@theme_window_flags_icon_activity},}##{?window_bell_flag,#{E:@theme_window_flags_icon_bell},}##{?window_silence_flag,#{E:@theme_window_flags_icon_silent},}##{?window_active,#{E:@theme_window_flags_icon_current},}##{?window_last_flag,#{E:@theme_window_flags_icon_last},}##{?window_marked_flag,#{E:@theme_window_flags_icon_mark},}##{?window_zoomed_flag,#{E:@theme_window_flags_icon_zoom},} "

set -ogq @theme_status_left_separator ""
set -ogq @theme_status_middle_separator ""
set -ogq @theme_status_right_separator " "
set -ogq @theme_status_connect_separator "yes" # yes, no

set -ogq @theme_status_module_text_bg "#{@thm_surface_0}"
