# vim:set ft=tmux:

# --> tmux-theme (Bearded Arc)
set -gq @thm_bg "#1c2433"
set -gq @thm_fg "#c3cfd9"

# Colors
set -gq @thm_rosewater "#F38CEC"
set -gq @thm_flamingo "#ee9cdd"
set -gq @thm_pink "#ee9cdd"
set -gq @thm_mauve "#bd93ff"
set -gq @thm_red "#ff5f7a"
set -gq @thm_maroon "#ff82a0"
set -gq @thm_peach "#FF955C"
set -gq @thm_yellow "#EACD61"
set -gq @thm_green "#9bdead"
set -gq @thm_teal "#12c7c4"
set -gq @thm_sky "#22ECDB"
set -gq @thm_sapphire "#6da4cd"
set -gq @thm_blue "#69C3FF"
set -gq @thm_lavender "#B78AFF"

# Surfaces and overlays
set -gq @thm_subtext_1 "#a1adb7"
set -gq @thm_subtext_0 "#ABB7C1"
set -gq @thm_overlay_2 "#626a79"
set -gq @thm_overlay_1 "#4e5665"
set -gq @thm_overlay_0 "#444c5b"
set -gq @thm_surface_2 "#3a4251"
set -gq @thm_surface_1 "#303847"
set -gq @thm_surface_0 "#262e3d"
set -gq @thm_mantle "#232b3a"
set -gq @thm_crust "#19212e"
