# vim:set ft=tmux:

# --> tmux-theme (Everforest Light)
set -gq @thm_bg "#fff9e8"
set -gq @thm_fg "#495157"

# Colors
set -gq @thm_rosewater "#ce8196"
set -gq @thm_flamingo "#ef6590"
set -gq @thm_pink "#ef6590"
set -gq @thm_mauve "#b67996"
set -gq @thm_red "#c85552"
set -gq @thm_maroon "#ce8196"
set -gq @thm_peach "#F7954F"
set -gq @thm_yellow "#dfa000"
set -gq @thm_green "#87a060"
set -gq @thm_teal "#69a59d"
set -gq @thm_sky "#89bfdc"
set -gq @thm_sapphire "#656c5f"
set -gq @thm_blue "#3a94c5"
set -gq @thm_lavender "#966986"

# Surfaces and overlays
set -gq @thm_subtext_1 "#272f35"
set -gq @thm_subtext_0 "#3b4349"
set -gq @thm_overlay_2 "#857F6E"
set -gq @thm_overlay_1 "#A39D8C"
set -gq @thm_overlay_0 "#B3AD9C"
set -gq @thm_surface_2 "#C2BCAB"
set -gq @thm_surface_1 "#D1CBBA"
set -gq @thm_surface_0 "#E0DAC9"
set -gq @thm_mantle "#f5efde"
set -gq @thm_crust "#ede7d6"
