# vim:set ft=tmux:

# --> tmux-theme (Gruvchad)
set -gq @thm_bg "#1e2122"
set -gq @thm_fg "#c0b196"

# Colors
set -gq @thm_rosewater "#ce8196"
set -gq @thm_flamingo "#ff75a0"
set -gq @thm_pink "#ff75a0"
set -gq @thm_mauve "#9385b4"
set -gq @thm_red "#ec6b64"
set -gq @thm_maroon "#ce8196"
set -gq @thm_peach "#e78a4e"
set -gq @thm_yellow "#d6b676"
set -gq @thm_green "#a9b665"
set -gq @thm_teal "#749689"
set -gq @thm_sky "#82b3a8"
set -gq @thm_sapphire "#6f8faf"
set -gq @thm_blue "#6d8dad"
set -gq @thm_lavender "#887aa9"

# Surfaces and overlays
set -gq @thm_subtext_1 "#d4be98"
set -gq @thm_subtext_0 "#c3b499"
set -gq @thm_overlay_2 "#606364"
set -gq @thm_overlay_1 "#575a5b"
set -gq @thm_overlay_0 "#484b4c"
set -gq @thm_surface_2 "#404344"
set -gq @thm_surface_1 "#393c3d"
set -gq @thm_surface_0 "#282b2c"
set -gq @thm_mantle "#222526"
set -gq @thm_crust "#1a1d1e"
