# vim:set ft=tmux:

# --> tmux-theme (One Light)
set -gq @thm_bg "#fafafa"
set -gq @thm_fg "#383a42"

# Colors
set -gq @thm_rosewater "#F07178"
set -gq @thm_flamingo "#ff75a0"
set -gq @thm_pink "#ff75a0"
set -gq @thm_mauve "#a28dcd"
set -gq @thm_red "#d84a3d"
set -gq @thm_maroon "#F07178"
set -gq @thm_peach "#FF6A00"
set -gq @thm_yellow "#c18401"
set -gq @thm_green "#7eca9c"
set -gq @thm_teal "#519ABA"
set -gq @thm_sky "#0b8ec6"
set -gq @thm_sapphire "#428bab"
set -gq @thm_blue "#4078f2"
set -gq @thm_lavender "#8e79b9"

# Surfaces and overlays
set -gq @thm_subtext_1 "#090a0b"
set -gq @thm_subtext_0 "#202227"
set -gq @thm_overlay_2 "#a2a2a3"
set -gq @thm_overlay_1 "#b0b0b1"
set -gq @thm_overlay_0 "#b7b7b8"
set -gq @thm_surface_2 "#cccccd"
set -gq @thm_surface_1 "#d4d4d5"
set -gq @thm_surface_0 "#dadadb"
set -gq @thm_mantle "#efeff0"
set -gq @thm_crust "#ececec"
