# vim:set ft=tmux:

# --> tmux-theme (Rosepine)
set -gq @thm_bg "#191724"
set -gq @thm_fg "#e0def4"

# Colors
set -gq @thm_rosewater "#f5799c"
set -gq @thm_flamingo "#ff83a6"
set -gq @thm_pink "#ff83a6"
set -gq @thm_mauve "#c4a7e7"
set -gq @thm_red "#eb6f92"
set -gq @thm_maroon "#f5799c"
set -gq @thm_peach "#f6c177"
set -gq @thm_yellow "#f6c177"
set -gq @thm_green "#b5f3bd"
set -gq @thm_teal "#6aadc8"
set -gq @thm_sky "#a3d6df"
set -gq @thm_sapphire "#86b9c2"
set -gq @thm_blue "#8bbec7"
set -gq @thm_lavender "#bb9ede"

# Surfaces and overlays
set -gq @thm_subtext_1 "#908caa"
set -gq @thm_subtext_0 "#e0def4"
set -gq @thm_overlay_2 "#5d5b68"
set -gq @thm_overlay_1 "#474552"
set -gq @thm_overlay_0 "#3f3d4a"
set -gq @thm_surface_2 "#353340"
set -gq @thm_surface_1 "#2d2b38"
set -gq @thm_surface_0 "#262431"
set -gq @thm_mantle "#201e2b"
set -gq @thm_crust "#13111e"
