# vim:set ft=tmux:

# --> tmux-theme (Tundra)
set -gq @thm_bg "#111827"
set -gq @thm_fg "#F3F4F6"

# Colors
set -gq @thm_rosewater "#FECDD3"
set -gq @thm_flamingo "#ff8e8e"
set -gq @thm_pink "#ff8e8e"
set -gq @thm_mauve "#BDB0E4"
set -gq @thm_red "#FCA5A5"
set -gq @thm_maroon "#FECDD3"
set -gq @thm_peach "#FBC19D"
set -gq @thm_yellow "#E8D4B0"
set -gq @thm_green "#B5E8B0"
set -gq @thm_teal "#719bd3"
set -gq @thm_sky "#BAE6FD"
set -gq @thm_sapphire "#9baaf2"
set -gq @thm_blue "#A5B4FC"
set -gq @thm_lavender "#b3a6da"

# Surfaces and overlays
set -gq @thm_subtext_1 "#3e4554"
set -gq @thm_subtext_0 "#E5E7EB"
set -gq @thm_overlay_2 "#5f6675"
set -gq @thm_overlay_1 "#4a5160"
set -gq @thm_overlay_0 "#3e4554"
set -gq @thm_surface_2 "#323948"
set -gq @thm_surface_1 "#282f3e"
set -gq @thm_surface_0 "#1e2534"
set -gq @thm_mantle "#171e2d"
set -gq @thm_crust "#0b1221"
